# Generated by Django 3.2.6 on 2022-01-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210320_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BIG', 'Big'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=50, null=True),
        ),
    ]
