# Generated by Django 3.2.6 on 2022-02-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('BIG', 'Big'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=50, null=True),
        ),
    ]
