# Generated by Django 3.2.6 on 2022-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Instructions',
            field=models.TextField(default=''),
        ),
    ]
